# -*- coding: utf-8 -*-
"""failsafe_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbVBxWyq3Dp615FN7frs49omRHTh-cM8
"""

# Install XGBoost and SHAP (Colab has pandas, sklearn, matplotlib pre-installed)
!pip install xgboost shap --quiet

print("✅ Libraries installed!")

# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import xgboost as xgb

# Explainable AI
import shap

# Save model
import joblib
import warnings
warnings.filterwarnings('ignore')

print("✅ All imports successful!")
print(f"📦 XGBoost version: {xgb.__version__}")
print(f"📦 SHAP version: {shap.__version__}")

# Load dataset from UCI with SSL verification disabled
import requests
import zipfile
import io
import ssl
from urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)

# URL for UCI Student Performance dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip"

print("📥 Downloading dataset...")
response = requests.get(url, verify=False)  # Disable SSL verification
z = zipfile.ZipFile(io.BytesIO(response.content))
z.extractall("student_data")

# Load the math scores
df = pd.read_csv("student_data/student-mat.csv", sep=';')

print(f"✅ Dataset loaded!")
print(f"📊 Shape: {df.shape[0]} students × {df.shape[1]} features")

# See the actual data
df.head()

# Basic statistics of numerical columns
df.describe()

# Let's see the distribution of final grades
plt.figure(figsize=(10, 5))
sns.histplot(df['G3'], bins=20, kde=True, color='skyblue')
plt.axvline(x=10, color='red', linestyle='--', label='Passing threshold (10)')
plt.title('Distribution of Final Grades (G3)')
plt.xlabel('Final Grade (0-20)')
plt.ylabel('Number of Students')
plt.legend()
plt.show()

# Quick count
passing = (df['G3'] >= 10).sum()
failing = (df['G3'] < 10).sum()
print(f"✅ Passing (≥10): {passing} students ({passing/len(df)*100:.1f}%)")
print(f"❌ At-Risk (<10): {failing} students ({failing/len(df)*100:.1f}%)")

# Correlation between G1, G2 and final grade G3
plt.figure(figsize=(12, 4))

# G1 vs G3
plt.subplot(1, 2, 1)
plt.scatter(df['G1'], df['G3'], alpha=0.5, c='teal')
plt.axhline(y=10, color='red', linestyle='--', label='Pass threshold')
plt.xlabel('First Period Grade (G1)')
plt.ylabel('Final Grade (G3)')
plt.title('Does G1 Predict Final Grade?')
plt.legend()

# G2 vs G3
plt.subplot(1, 2, 2)
plt.scatter(df['G2'], df['G3'], alpha=0.5, c='orange')
plt.axhline(y=10, color='red', linestyle='--', label='Pass threshold')
plt.xlabel('Second Period Grade (G2)')
plt.ylabel('Final Grade (G3)')
plt.title('Does G2 Predict Final Grade?')
plt.legend()

plt.tight_layout()
plt.show()

# Correlation numbers
print(f"📊 Correlation G1→G3: {df['G1'].corr(df['G3']):.3f}")
print(f"📊 Correlation G2→G3: {df['G2'].corr(df['G3']):.3f}")

# Correlation heatmap - find ALL important features
plt.figure(figsize=(14, 8))

# Select only numerical columns
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
corr_matrix = df[num_cols].corr()

# Plot heatmap focused on G3 correlations
sns.heatmap(corr_matrix[['G3']].sort_values(by='G3', ascending=False),
            annot=True, cmap='RdYlGn', center=0, fmt='.2f')

plt.title('What Correlates with Final Grade (G3)?')
plt.show()

print("🟢 GREEN = Positive impact on grades")
print("🔴 RED = Negative impact on grades")

# Create binary target: 1 = Pass (G3>=10), 0 = Fail (G3<10)
df['pass'] = (df['G3'] >= 10).astype(int)

# Check the distribution
print("📊 Target Variable (Pass/Fail):")
print(df['pass'].value_counts())
print(f"\nFail (0): {(df['pass']==0).sum()} students ({(df['pass']==0).mean()*100:.1f}%)")
print(f"Pass (1): {(df['pass']==1).sum()} students ({(df['pass']==1).mean()*100:.1f}%)")

# Show first few rows with new column
print("\n📋 Sample data with new target column:")
print(df[['G3', 'pass']].head(10))

# Visualize target distribution
plt.figure(figsize=(8, 5))

# Get counts in correct order
counts = [df['pass'].value_counts().get(0, 0), df['pass'].value_counts().get(1, 0)]
labels = ['Fail (0)', 'Pass (1)']

# Bar chart
colors = ['#ff6b6b', '#51cf66']
bars = plt.bar(labels, counts, color=colors)

# Add count labels on bars
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(height)}\n({height/len(df)*100:.1f}%)',
             ha='center', va='bottom', fontsize=14, fontweight='bold')

plt.title('Target Variable Distribution', fontsize=16)
plt.ylabel('Number of Students', fontsize=12)
plt.ylim(0, 320)
plt.show()

# Calculate imbalance ratio
fail_count = (df['pass']==0).sum()
pass_count = (df['pass']==1).sum()
ratio = pass_count / fail_count

print(f"❌ Fail: {fail_count} students ({fail_count/len(df)*100:.1f}%)")
print(f"✅ Pass: {pass_count} students ({pass_count/len(df)*100:.1f}%)")
print(f"⚖️ Imbalance Ratio: {ratio:.1f}:1 (Pass:Fail)")
print(f"📊 Majority class (Pass) is {ratio:.1f}x larger than minority class (Fail)")

if ratio > 2:
    print("\n⚠️ DATA IS IMBALANCED! We'll need to handle this.")
    print("   If we don't, model might just predict 'Pass' for everyone!")
else:
    print("\n✅ Data is reasonably balanced.")

# Step 1: Define what we want to predict
target = 'pass'

# Step 2: Remove columns the model shouldn't use
# G3 = final grade (this IS what we're predicting - can't use it!)
# G1, G2 = earlier grades (we'll discuss if we should keep or drop)
# pass = our target variable

drop_cols = ['G3', 'pass']  # Always drop these
# We'll decide about G1 and G2 after discussion

X = df.drop(columns=drop_cols)
y = df[target]

print(f"📊 Features (X): {X.shape[1]} columns")
print(f"🎯 Target (y): {y.name}")
print(f"\n📋 Feature columns:")
for i, col in enumerate(X.columns, 1):
    print(f"   {i}. {col}")

# Separate columns by type
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("="*50)
print("📝 CATEGORICAL COLUMNS (Need encoding)")
print("="*50)
for i, col in enumerate(categorical_cols, 1):
    unique_vals = df[col].unique()
    print(f"{i}. {col}: {len(unique_vals)} unique values → {list(unique_vals)}")

print(f"\n{'='*50}")
print("🔢 NUMERICAL COLUMNS (Ready to use)")
print("="*50)
for i, col in enumerate(numerical_cols, 1):
    print(f"{i}. {col}")

print(f"\n📊 Total: {len(categorical_cols)} categorical + {len(numerical_cols)} numerical = {len(categorical_cols)+len(numerical_cols)} features")

# Copy X to avoid modifying original
X_encoded = X.copy()

# List of binary columns (2 unique values)
binary_cols = ['school', 'sex', 'address', 'famsize', 'Pstatus',
               'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
               'higher', 'internet', 'romantic']

print("🔄 Encoding binary columns...")

for col in binary_cols:
    # Get the two unique values
    vals = X_encoded[col].unique()

    # Create mapping: first value → 0, second value → 1
    mapping = {vals[0]: 0, vals[1]: 1}

    # Apply mapping
    X_encoded[col] = X_encoded[col].map(mapping)

    print(f"   {col}: {mapping}")

print(f"\n✅ {len(binary_cols)} binary columns encoded!")

# Handle multi-category columns with One-Hot Encoding
multi_cols = ['Mjob', 'Fjob', 'reason', 'guardian']

print("🔄 One-Hot Encoding multi-category columns...")

for col in multi_cols:
    # Get one-hot encoded dataframe for this column
    dummies = pd.get_dummies(X_encoded[col], prefix=col, drop_first=True)

    # Convert True/False to 1/0
    dummies = dummies.astype(int)

    # Drop original column and add new dummy columns
    X_encoded = pd.concat([X_encoded.drop(columns=[col]), dummies], axis=1)

    print(f"   {col}: Created {dummies.shape[1]} new columns → {list(dummies.columns)}")

print(f"\n✅ One-Hot Encoding complete!")
print(f"   Original shape: {X.shape}")
print(f"   New shape: {X_encoded.shape}")
print(f"   Added {X_encoded.shape[1] - X.shape[1]} new columns")

# Verify all columns are numeric
print("="*50)
print("🔍 FINAL VERIFICATION")
print("="*50)

# Check data types
dtype_counts = X_encoded.dtypes.value_counts()
print(f"\n📊 Data Types:")
for dtype, count in dtype_counts.items():
    print(f"   {dtype}: {count} columns")

# Check for any missing values
total_missing = X_encoded.isnull().sum().sum()
print(f"\n🔍 Missing Values: {total_missing}")

# Show first few rows
print(f"\n📋 First 3 rows of processed data:")
display(X_encoded.head(3))

# All columns list
print(f"\n📝 All {len(X_encoded.columns)} features:")
for i, col in enumerate(X_encoded.columns, 1):
    print(f"   {i}. {col}")

from sklearn.model_selection import train_test_split

# Split: 80% training, 20% testing
# stratify=y keeps the same 67/33 pass/fail ratio in both sets
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("="*50)
print("📊 DATA SPLIT RESULTS")
print("="*50)

print(f"\n🔵 TRAINING SET")
print(f"   Samples: {X_train.shape[0]} students")
print(f"   Fail: {(y_train==0).sum()} ({(y_train==0).mean()*100:.1f}%)")
print(f"   Pass: {(y_train==1).sum()} ({(y_train==1).mean()*100:.1f}%)")

print(f"\n🟡 TEST SET")
print(f"   Samples: {X_test.shape[0]} students")
print(f"   Fail: {(y_test==0).sum()} ({(y_test==0).mean()*100:.1f}%)")
print(f"   Pass: {(y_test==1).sum()} ({(y_test==1).mean()*100:.1f}%)")

print(f"\n✅ Ratio maintained: ~67/33 in both sets")

# Calculate imbalance ratio for scale_pos_weight
fail_count = (y_train == 0).sum()
pass_count = (y_train == 1).sum()
scale_weight = pass_count / fail_count

print("="*50)
print("🤖 TRAINING XGBOOST MODEL")
print("="*50)
print(f"\n📊 Imbalance Handling:")
print(f"   Pass students in training: {pass_count}")
print(f"   Fail students in training: {fail_count}")
print(f"   scale_pos_weight: {scale_weight:.2f}")
print(f"   → Model penalized {scale_weight:.1f}x more for missing a failing student")

# Create and train the model
model = xgb.XGBClassifier(
    scale_pos_weight=scale_weight,  # ← THIS handles imbalance!
    random_state=42,
    eval_metric='logloss'
)

# Train on training data
model.fit(X_train, y_train)

print(f"\n✅ Model trained successfully!")

# Make predictions on test set (students model has NEVER seen)
y_pred = model.predict(X_test)

print("="*50)
print("📊 MODEL EVALUATION")
print("="*50)

# 1. Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\n🎯 Accuracy: {accuracy:.2%}")
print(f"   Correctly predicted {int(accuracy*len(y_test))} out of {len(y_test)} students")

# 2. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f"\n📋 Confusion Matrix:")
print(f"   ┌─────────────────────┬─────────────────────┐")
print(f"   │                     │    PREDICTED        │")
print(f"   │                     ├──────────┬──────────┤")
print(f"   │                     │   FAIL   │   PASS   │")
print(f"   ├──────────┬──────────┼──────────┼──────────┤")
print(f"   │ ACTUAL   │  FAIL    │    {cm[0,0]:>2}    │    {cm[0,1]:>2}    │")
print(f"   │          │  PASS    │     {cm[1,0]:>2}   │    {cm[1,1]:>3}   │")
print(f"   └──────────┴──────────┴──────────┴──────────┘")

# 3. Detailed Metrics
print(f"\n📊 Detailed Metrics:")
print(f"   True Negatives  (TN): {cm[0,0]} → Correctly predicted FAIL")
print(f"   False Positives (FP): {cm[0,1]} → Predicted FAIL but student PASSED (false alarm)")
print(f"   False Negatives (FN): {cm[1,0]} → Predicted PASS but student FAILED (MISSED!)")
print(f"   True Positives  (TP): {cm[1,1]} → Correctly predicted PASS")

# 4. Classification Report
print(f"\n📈 Classification Report:")
print(classification_report(y_test, y_pred, target_names=['FAIL', 'PASS']))

"""## 📈 Model Optimization: Hyperparameter Tuning with GridSearchCV

Let's try to improve the model's performance by systematically searching for the best hyperparameters using `GridSearchCV`. This will train multiple models with different combinations of parameters and evaluate them using cross-validation.
"""

from sklearn.model_selection import GridSearchCV, StratifiedKFold

print("="*50)
print("🧪 HYPERPARAMETER TUNING WITH GridSearchCV")
print("="*50)

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300], # Number of boosting rounds
    'learning_rate': [0.05, 0.1, 0.2], # Step size shrinkage
    'max_depth': [1,3, 5, 7], # Maximum depth of a tree
    'subsample': [0.8, 1.0], # Subsample ratio of the training instance
    'colsample_bytree': [0.8, 1.0] # Subsample ratio of columns when constructing each tree
}

# Initialize XGBoost Classifier with the previously calculated scale_pos_weight
xgb_tuned = xgb.XGBClassifier(
    scale_pos_weight=scale_weight, # Keep the imbalance handling fixed
    random_state=42,
    eval_metric='logloss' # Consistent evaluation metric
)

# Set up StratifiedKFold for cross-validation to maintain class distribution
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Initialize GridSearchCV
# 'f1_macro' is a good metric for imbalanced classification as it considers both classes
grid_search = GridSearchCV(
    estimator=xgb_tuned,
    param_grid=param_grid,
    scoring='f1_macro',
    cv=kf,
    verbose=1,
    n_jobs=-1 # Use all available cores
)

print("\n🚀 Starting Grid Search...")
grid_search.fit(X_train, y_train)

print("\n✅ Grid Search complete!")

print("\n✨ Best parameters found:")
print(grid_search.best_params_)

print("\n🏆 Best cross-validation F1-macro score:")
print(f"{grid_search.best_score_:.4f}")

# Get the best model
best_model = grid_search.best_estimator_

print("\n📊 Evaluating the best model on the test set...")
y_pred_tuned = best_model.predict(X_test)

# Evaluate the tuned model
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
cm_tuned = confusion_matrix(y_test, y_pred_tuned)

print("\n==================================================")
print("📊 TUNED MODEL EVALUATION")
print("==================================================")
print(f"\n🎯 Accuracy: {accuracy_tuned:.2%}")
print(f"   Correctly predicted {int(accuracy_tuned*len(y_test))} out of {len(y_test)} students")

print(f"\n📋 Confusion Matrix:")
print(f"   ┌─────────────────────┬─────────────────────┐")
print(f"   │                     │    PREDICTED        │")
print(f"   │                     ├──────────┬──────────┤")
print(f"   │                     │   FAIL   │   PASS   │")
print(f"   ├──────────┬──────────┼──────────┼──────────┤")
print(f"   │ ACTUAL   │  FAIL    │    {cm_tuned[0,0]:>2}    │    {cm_tuned[0,1]:>2}    │")
print(f"   │          │  PASS    │     {cm_tuned[1,0]:>2}   │    {cm_tuned[1,1]:>3}   │")
print(f"   └──────────┴──────────┴──────────┴──────────┘")

print(f"\n📈 Classification Report:")
print(classification_report(y_test, y_pred_tuned, target_names=['FAIL', 'PASS']))

"""## 📦 Save the Tuned Model

Now that we have a tuned model, let's save it along with its preprocessing configuration for deployment.
"""

import joblib
from datetime import datetime
import os
import pandas as pd # Needed for the embedded preprocessing function (map, get_dummies)
from google.colab import files # Import files for direct download

# Get classification report as dictionary for the TUNED model
report_dict_tuned = classification_report(y_test, y_pred_tuned, output_dict=True)

# Ensure keys are correct ('0' and '1' or 'FAIL' and 'PASS')
fail_key_tuned = '0' if '0' in report_dict_tuned else 'FAIL'
pass_key_tuned = '1' if '1' in report_dict_tuned else 'PASS'

# --- Define preprocessing configuration to embed directly ---
# These mappings were derived from the data in previous steps
binary_mappings_for_bundle = {
    'school': {'GP': 0, 'MS': 1},
    'sex': {'F': 0, 'M': 1},
    'address': {'U': 0, 'R': 1},
    'famsize': {'GT3': 0, 'LE3': 1},
    'Pstatus': {'A': 0, 'T': 1},
    'schoolsup': {'yes': 0, 'no': 1},
    'famsup': {'no': 0, 'yes': 1},
    'paid': {'no': 0, 'yes': 1},
    'activities': {'no': 0, 'yes': 1},
    'nursery': {'yes': 0, 'no': 1},
    'higher': {'yes': 0, 'no': 1},
    'internet': {'no': 0, 'yes': 1},
    'romantic': {'no': 0, 'yes': 1}
}
multi_cols_for_bundle = ['Mjob', 'Fjob', 'reason', 'guardian']

# The full preprocessing function as a string for embedding
preprocessing_function_str = """
import pandas as pd
import numpy as np

def preprocess_new_data_for_bundle(raw_df, feature_names, binary_maps, multi_category_cols):
    df = raw_df.copy()

    # Apply binary mappings
    for col, mapping in binary_maps.items():
        if col in df.columns:
            df[col] = df[col].map(mapping).fillna(0).astype(int)

    # Apply one-hot encoding for multi-category columns
    for col in multi_category_cols:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col).astype(int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

    # Ensure all expected feature_names are present, filling missing with 0
    # and dropping extra columns not in feature_names
    # This also ensures the order of columns
    processed_df = pd.DataFrame(columns=feature_names)
    for col in feature_names:
        if col in df.columns:
            processed_df[col] = df[col]
        else:
            processed_df[col] = 0 # Fill missing columns with 0

    return processed_df
"""


# Create a bundle with everything the backend needs for the TUNED model
tuned_model_bundle = {
    'model': best_model,
    'feature_names': list(X_encoded.columns), # Use X_encoded columns as feature names
    'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'metrics': {
        'accuracy': accuracy_tuned,
        'fail_recall': report_dict_tuned[fail_key_tuned]['recall'],
        'pass_recall': report_dict_tuned[pass_key_tuned]['recall']
    },
    'scale_pos_weight': scale_weight,
    'dataset_shape': X_encoded.shape,
    'preprocessing': { # Embed preprocessing configuration directly
        'binary_mappings': binary_mappings_for_bundle,
        'multi_cols': multi_cols_for_bundle,
        'function_str': preprocessing_function_str # Store the function as a string
    }
}

# Define the filename
model_filename = 'failsafe_model_tuned.pkl'

# Save to file
joblib.dump(tuned_model_bundle, model_filename)

print("="*50)
print("💾 TUNED MODEL SAVED!")
print("="*50)
print(f"\n📦 File: {model_filename}")
print(f"\n📊 Bundle Contents:")
for key, value in tuned_model_bundle.items():
    if key == 'model':
        print(f"   {key}: <XGBoost Model Object>")
    elif key == 'preprocessing':
        print(f"   {key}: {{'binary_mappings': <dict>, 'multi_cols': <list>, 'function_str': '<preprocessing_code_string>'}}")
    else:
        print(f"   {key}: {value}")

file_size_tuned = os.path.getsize(model_filename) / 1024
print(f"\n📏 File size: {file_size_tuned:.1f} KB")

# Direct download using google.colab.files
try:
    files.download(model_filename)
    print(f"\n✅ Successfully triggered download for '{model_filename}'")
except Exception as e:
    print(f"\n❌ Error triggering download: {e}")
    print("   Please check if the file exists and you have permissions.")

"""## 🚀 Model Ensemble: Stacking Classifier

Let's explore if combining multiple models through stacking can lead to even better performance. We'll use a few diverse base models and a meta-learner to make the final prediction.
"""

from sklearn.ensemble import StackingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, StratifiedKFold # Added for tuning

print("="*50)
print("INDIVIDUAL BASE MODEL TUNING")
print("="*50)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# --- Tune RandomForestClassifier ---
print("\n🚀 Tuning RandomForestClassifier...")
rf_classifier = RandomForestClassifier(random_state=42)
param_grid_rf = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10],
    'min_samples_leaf': [1, 2]
}
grid_search_rf = GridSearchCV(estimator=rf_classifier, param_grid=param_grid_rf, scoring='f1_macro', cv=kf, verbose=0, n_jobs=-1)
grid_search_rf.fit(X_train, y_train)
best_rf = grid_search_rf.best_estimator_
print(f"✅ Best RandomForest: {grid_search_rf.best_params_}")

# --- Tune KNeighborsClassifier ---
print("\n🚀 Tuning KNeighborsClassifier...")
knn_classifier = KNeighborsClassifier()
param_grid_knn = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance']
}
grid_search_knn = GridSearchCV(estimator=knn_classifier, param_grid=param_grid_knn, scoring='f1_macro', cv=kf, verbose=0, n_jobs=-1)
grid_search_knn.fit(X_train, y_train)
best_knn = grid_search_knn.best_estimator_
print(f"✅ Best KNeighbors: {grid_search_knn.best_params_}")

# --- Tune SVC ---
print("\n🚀 Tuning SVC...")
svc_classifier = SVC(probability=True, random_state=42)
param_grid_svc = {
    'C': [0.1, 1, 10],
    'kernel': ['rbf', 'linear']
}
grid_search_svc = GridSearchCV(estimator=svc_classifier, param_grid=param_grid_svc, scoring='f1_macro', cv=kf, verbose=0, n_jobs=-1)
grid_search_svc.fit(X_train, y_train)
best_svc = grid_search_svc.best_estimator_
print(f"✅ Best SVC: {grid_search_svc.best_params_}")

# GaussianNB has no hyperparameters to tune, so we use it directly
best_gnb = GaussianNB()
print("\n✅ GaussianNB added (no tuning needed).")


print("\n" + "="*50)
print("STACKING CLASSIFIER WITH TUNED XGBOOST META-LEARNER")
print("="*50)

# Define base models using the *best* estimators from individual tuning
estimators = [
    ('xgb_base', best_model), # The previously tuned best_model
    ('rf', best_rf),
    ('knn', best_knn),
    ('svc', best_svc),
    ('gnb', best_gnb)
]

# Define the meta-learner (now an XGBClassifier)
xgb_meta_learner = xgb.XGBClassifier(
    scale_pos_weight=scale_weight, # Apply imbalance handling to meta-learner
    random_state=42,
    eval_metric='logloss',
    use_label_encoder=False # Suppress warning for older XGBoost versions
)

# Create the Stacking Classifier (without specific meta-learner params yet)
stacking_base = StackingClassifier(
    estimators=estimators,
    final_estimator=xgb_meta_learner, # Assign the XGBoost meta-learner
    cv=5, # Using 5-fold cross-validation for meta-learner training
    n_jobs=-1, # Use all available cores
    passthrough=True, # Pass raw features to the final estimator as well
    verbose=0 # Set verbose to 0 to avoid excessive output during inner folds of grid search
)

# Define parameter grid for the meta-learner
# Parameters must be prefixed with 'final_estimator__'
param_grid_stacking = {
    'final_estimator__n_estimators': [50, 100], # Fewer estimators for meta-learner
    'final_estimator__learning_rate': [0.01, 0.1],
    'final_estimator__max_depth': [1, 3], # Smaller max_depth for meta-learner
    'final_estimator__subsample': [0.8, 1.0],
    'final_estimator__colsample_bytree': [0.8, 1.0]
}

# Initialize GridSearchCV for the Stacking Classifier
stacking_grid_search = GridSearchCV(
    estimator=stacking_base,
    param_grid=param_grid_stacking,
    scoring='f1_macro', # Use f1_macro for imbalanced classification
    cv=kf,
    verbose=1, # Verbose for the outer grid search
    n_jobs=-1 # Use all available cores
)

print("\n🚀 Starting Grid Search for Stacking Model with Tuned Meta-Learner...")
stacking_grid_search.fit(X_train, y_train)

print("\n✅ Grid Search for Stacking Model complete!")

print("\n✨ Best parameters for Stacking Meta-Learner found:")
print(stacking_grid_search.best_params_)

print("\n🏆 Best cross-validation F1-macro score for Stacking Model:")
print(f"{stacking_grid_search.best_score_:.4f}")

# Get the best stacking model from the grid search
stacking_model = stacking_grid_search.best_estimator_

print("\n✅ Stacking model (with tuned XGBoost meta-learner) trained successfully!")

# Make predictions with the stacking model
y_pred_stacking = stacking_model.predict(X_test)

# Evaluate the stacking model
accuracy_stacking = accuracy_score(y_test, y_pred_stacking)
cm_stacking = confusion_matrix(y_test, y_pred_stacking)
report_stacking = classification_report(y_test, y_pred_stacking, target_names=['FAIL', 'PASS'])

print("\n==================================================")
print("📊 STACKING MODEL EVALUATION")
print("==================================================")
print(f"\n🎯 Accuracy: {accuracy_stacking:.2%}")
print(f"   Correctly predicted {int(accuracy_stacking*len(y_test))} out of {len(y_test)} students")

print(f"\n📋 Confusion Matrix:")
print(f"   ┌─────────────────────┬─────────────────────┐")
print(f"   │                     │    PREDICTED        │")
print(f"   │                     ├──────────┬──────────┤")
print(f"   │                     │   FAIL   │   PASS   │")
print(f"   ├──────────┬──────────┼──────────┼──────────┤")
print(f"   │ ACTUAL   │  FAIL    │    {cm_stacking[0,0]:>2}    │    {cm_stacking[0,1]:>2}    │")
print(f"   │          │  PASS    │     {cm_stacking[1,0]:>2}   │    {cm_stacking[1,1]:>3}   │")
print(f"   └──────────┴──────────┴──────────┴──────────┘")

print(f"\n📈 Classification Report:")
print(report_stacking)

print("\n==================================================")
print("COMPARISON: TUNED XGBOOST vs STACKING")
print("==================================================")

print(f"\n**Tuned XGBoost:**")
print(f"Accuracy: {accuracy_tuned:.2%}")
print(classification_report(y_test, y_pred_tuned, target_names=['FAIL', 'PASS']))

print(f"\n**Stacking Classifier:**")
print(f"Accuracy: {accuracy_stacking:.2%}")
print(report_stacking)

if accuracy_stacking > accuracy_tuned:
    print("\n🎉 The Stacking Classifier achieved higher accuracy!")
elif accuracy_stacking < accuracy_tuned:
    print("\nℹ️ The Tuned XGBoost performed slightly better in terms of accuracy.")
else:
    print("\n⚖️ Both models achieved similar accuracy.")

# For specific needs, e.g., if 'FAIL' recall is most important:
# Extract FAIL recall for comparison
report_tuned_dict = classification_report(y_test, y_pred_tuned, output_dict=True)
report_stacking_dict = classification_report(y_test, y_pred_stacking, output_dict=True)

# Assuming '0' is FAIL and '1' is PASS from previous analysis
fail_recall_tuned = report_tuned_dict['0']['recall']
fail_recall_stacking = report_stacking_dict['0']['recall']

print(f"\n**FAIL Recall Comparison:**")
print(f"Tuned XGBoost FAIL Recall: {fail_recall_tuned:.2%}")
print(f"Stacking Classifier FAIL Recall: {fail_recall_stacking:.2%}")

if fail_recall_stacking > fail_recall_tuned:
    print("\n🎉 The Stacking Classifier is better at identifying failing students!")
elif fail_recall_stacking < fail_recall_tuned:
    print("\nℹ️ The Tuned XGBoost is better at identifying failing students.")
else:
    print("\n⚖️ Both models are similar at identifying failing students.")

import joblib
from datetime import datetime
import os
from google.colab import files # Import files for direct download

# Get classification report as dictionary for the STACKED model
report_dict_stacking = classification_report(y_test, y_pred_stacking, output_dict=True)

# Ensure keys are correct ('0' and '1' or 'FAIL' and 'PASS')
fail_key_stacking = '0' if '0' in report_dict_stacking else 'FAIL'
pass_key_stacking = '1' if '1' in report_dict_stacking else 'PASS'

# Create a bundle with everything the backend needs for the STACKED model
stacked_model_bundle = {
    'model': stacking_model,
    'feature_names': list(X_encoded.columns), # Use X_encoded columns as feature names
    'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'metrics': {
        'accuracy': accuracy_stacking,
        'fail_recall': report_dict_stacking[fail_key_stacking]['recall'],
        'pass_recall': report_dict_stacking[pass_key_stacking]['recall']
    },
    'scale_pos_weight': scale_weight,
    'dataset_shape': X_encoded.shape,
    'preprocessing': { # Embed preprocessing configuration directly
        'binary_mappings': binary_mappings_for_bundle, # Reusing from previous save
        'multi_cols': multi_cols_for_bundle,           # Reusing from previous save
        'function_str': preprocessing_function_str      # Reusing from previous save
    }
}

# Define the filename
model_filename_stacked = 'failsafe_model_stacked.pkl'

# Save to file
joblib.dump(stacked_model_bundle, model_filename_stacked)

print("="*50)
print("💾 STACKED MODEL SAVED!")
print("="*50)
print(f"\n📦 File: {model_filename_stacked}")
print(f"\n📊 Bundle Contents:")
for key, value in stacked_model_bundle.items():
    if key == 'model':
        print(f"   {key}: <StackingClassifier Model Object>")
    elif key == 'preprocessing':
        print(f"   {key}: {{'binary_mappings': <dict>, 'multi_cols': <list>, 'function_str': '<preprocessing_code_string>'}}")
    else:
        print(f"   {key}: {value}")

file_size_stacked = os.path.getsize(model_filename_stacked) / 1024
print(f"\n📏 File size: {file_size_stacked:.1f} KB")

# Direct download using google.colab.files
try:
    files.download(model_filename_stacked)
    print(f"\n✅ Successfully triggered download for '{model_filename_stacked}'")
except Exception as e:
    print(f"\n❌ Error triggering download: {e}")
    print("   Please check if the file exists and you have permissions.")

"""---

### ✅ Preprocessing Configuration Embedded in Tuned Model

The `failsafe_model_tuned.pkl` file (saved in the previous cell) now includes all the necessary preprocessing details:
- `feature_names`: The exact list and order of features expected by the model.
- `binary_mappings`: The dictionary of mappings for binary categorical features.
- `multi_cols`: The list of features that require one-hot encoding.
- `function_str`: The full Python source code of a `preprocess_new_data_for_bundle` function, which can be executed to transform raw input data into the format the model expects.

This ensures that when you load `failsafe_model_tuned.pkl` in your backend or deployment environment, you have everything you need to preprocess new data correctly before making predictions.

---

### 🧹 Cleanup: Remove Redundant Cells

To clean up your notebook and remove now-redundant code, please manually delete the following cells, which were primarily used for the original model saving or separate preprocessing function definitions and verifications:

- Cell `GtogDoJrM0FF`: Original model saving.
- Cell `TCUiLUvcNiKG`: Definition of `preprocess_new_data` function (now embedded).
- Cell `SentTRFFOQap`: Demo of `preprocess_new_data`.
- Cell `RWIXULYgOVOm`: Updating original model bundle with preprocessing.
- Cell `CfK6JGvBObSM`: Printing final preprocessing code.
- Cell `mRWtl1swOvuq`: Empty cell.
- Cell `824f98fe`: Markdown for model verification.
- Cell `2c420716`: Loading `failsafe_model.pkl` for verification.
- Cell `2c7d34ff`: Demo with loaded model and preprocessing.
"""

# Get feature importance from the model
importance_df = pd.DataFrame({
    'feature': X_encoded.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

# Plot top 15 features
plt.figure(figsize=(10, 6))
top_features = importance_df.head(15)

plt.barh(range(len(top_features)), top_features['importance'], color='teal')
plt.yticks(range(len(top_features)), top_features['feature'])
plt.gca().invert_yaxis()  # Most important at top
plt.xlabel('Importance Score')
plt.title('Top 15 Features - What Drives Failure Prediction?')

# Add values on bars
for i, v in enumerate(top_features['importance']):
    plt.text(v + 0.002, i, f'{v:.3f}', va='center')

plt.tight_layout()
plt.show()

# Print full list
print("\n📊 COMPLETE FEATURE IMPORTANCE RANKING:")
print("="*50)
for i, row in importance_df.iterrows():
    print(f"{importance_df.index.get_loc(i)+1:2d}. {row['feature']:<25s} {row['importance']:.4f}")

# Investigate school differences
print("="*50)
print("🏫 SCHOOL COMPARISON")
print("="*50)

print("\n📊 Pass Rates by School:")
school_stats = df.groupby('school').agg(
    Students=('pass', 'count'),
    Pass_Rate=('pass', 'mean'),
    Avg_Grade=('G3', 'mean'),
    Avg_Absences=('absences', 'mean')
)
school_stats['Pass_Rate'] = school_stats['Pass_Rate'] * 100
print(school_stats)

print("\n📊 Feature Averages by School:")
school_compare = df.groupby('school')[['G1', 'G2', 'G3', 'absences',
                                         'studytime', 'failures']].mean()
print(school_compare)

# Initialize SHAP explainer
print("🔄 Initializing SHAP explainer...")
explainer = shap.TreeExplainer(model)

# Calculate SHAP values for test set
print("📊 Calculating SHAP values...")
shap_values = explainer.shap_values(X_test)

print("✅ SHAP values calculated!")
print(f"   Shape: {shap_values.shape}")
print(f"   → {shap_values.shape[0]} students × {shap_values.shape[1]} features")

# Summary plot - overall feature impact
print("\n📊 SHAP Summary Plot...")
shap.summary_plot(shap_values, X_test, feature_names=X_encoded.columns, show=False)
plt.title('SHAP Feature Impact on Failure Risk')
plt.tight_layout()
plt.show()

# Check which class SHAP is explaining
print("🔍 Understanding SHAP Direction:")
print("="*50)

# For binary classification, shap_values has shape (n_samples, n_features)
# Let's check one student to understand direction
student_idx = 0  # First test student

print(f"\n📋 Student {student_idx}:")
print(f"   Actual: {'PASS' if y_test.iloc[student_idx] == 1 else 'FAIL'}")
print(f"   Predicted probability of FAIL: {model.predict_proba(X_test.iloc[[student_idx]])[0][0]:.3f}")
print(f"   Predicted probability of PASS: {model.predict_proba(X_test.iloc[[student_idx]])[0][1]:.3f}")

# Get SHAP values for this student
student_shap = shap_values[student_idx]
base_value = explainer.expected_value

print(f"\n📊 Base value (expected): {base_value:.4f}")
print(f"   Sum of SHAP values: {student_shap.sum():.4f}")
print(f"   Base + SHAP = Model output: {base_value + student_shap.sum():.4f}")

# Pick a student who actually FAILED
failing_students = X_test[y_test == 0]
failing_indices = failing_students.index

if len(failing_indices) > 0:
    student_idx = failing_indices[0]  # First failing student

    print("="*50)
    print("🔍 INDIVIDUAL STUDENT EXPLANATION")
    print("="*50)

    print(f"\n📋 Student ID: {student_idx}")
    print(f"   Actual Outcome: FAIL ❌")

    # Get prediction probability
    proba = model.predict_proba(X_test.loc[[student_idx]])
    print(f"   Model's FAIL probability: {proba[0][0]:.1%}")
    print(f"   Model's PASS probability: {proba[0][1]:.1%}")

    # SHAP Waterfall plot
    print("\n📊 SHAP Explanation (Why this prediction?):")
    shap.waterfall_plot(
        shap.Explanation(
            values=shap_values[X_test.index.get_loc(student_idx)],
            base_values=explainer.expected_value,
            data=X_test.loc[student_idx].values,
            feature_names=X_test.columns
        ),
        show=False
    )
    plt.title(f'SHAP Breakdown for Student {student_idx}')
    plt.tight_layout()
    plt.show()

    # Text summary - top risk factors
    student_shap = shap_values[X_test.index.get_loc(student_idx)]
    shap_df = pd.DataFrame({
        'feature': X_test.columns,
        'shap_value': student_shap,
        'feature_value': X_test.loc[student_idx].values
    })

    # Sort by absolute SHAP value
    shap_df['abs_shap'] = abs(shap_df['shap_value'])
    shap_df = shap_df.sort_values('abs_shap', ascending=False)

    print("\n🔝 TOP FACTORS:")
    for i, row in shap_df.head(10).iterrows():
        direction = "🟢 PROTECTIVE" if row['shap_value'] > 0 else "🔴 RISK"
        print(f"   {direction}: {row['feature']} = {row['feature_value']:.2f} (impact: {row['shap_value']:+.3f})")
else:
    print("No failing students in test set!")

# Pick a student who PASSED
passing_students = X_test[y_test == 1]
passing_indices = passing_students.index

if len(passing_indices) > 0:
    student_idx = passing_indices[0]

    print("="*50)
    print("🟢 PASSING STUDENT EXPLANATION")
    print("="*50)

    proba = model.predict_proba(X_test.loc[[student_idx]])
    print(f"\n📋 Student ID: {student_idx}")
    print(f"   Actual Outcome: PASS ✅")
    print(f"   Model's FAIL probability: {proba[0][0]:.1%}")

    student_shap = shap_values[X_test.index.get_loc(student_idx)]
    shap_df = pd.DataFrame({
        'feature': X_test.columns,
        'shap_value': student_shap,
        'feature_value': X_test.loc[student_idx].values
    })
    shap_df['abs_shap'] = abs(shap_df['shap_value'])
    shap_df = shap_df.sort_values('abs_shap', ascending=False)

    print("\n🔝 TOP FACTORS:")
    for i, row in shap_df.head(10).iterrows():
        direction = "🟢 PROTECTIVE" if row['shap_value'] > 0 else "🔴 RISK"
        print(f"   {direction}: {row['feature']} = {row['feature_value']:.2f} (impact: {row['shap_value']:+.3f})")

import joblib
from datetime import datetime
import os

# Get classification report as dictionary
report_dict = classification_report(y_test, y_pred, output_dict=True)

# Check what keys exist
print("Available keys in report:", list(report_dict.keys()))

# Get recall values (keys might be '0' and '1' instead of 'FAIL' and 'PASS')
fail_key = '0' if '0' in report_dict else 'FAIL'
pass_key = '1' if '1' in report_dict else 'PASS'

# Create a bundle with everything the backend needs
model_bundle = {
    'model': model,
    'feature_names': list(X_encoded.columns),
    'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'metrics': {
        'accuracy': accuracy,
        'fail_recall': report_dict[fail_key]['recall'],
        'pass_recall': report_dict[pass_key]['recall']
    },
    'scale_pos_weight': scale_weight,
    'dataset_shape': X_encoded.shape
}

# Save to file
joblib.dump(model_bundle, 'failsafe_model.pkl')

print("="*50)
print("💾 MODEL SAVED!")
print("="*50)
print(f"\n📦 File: failsafe_model.pkl")
print(f"\n📊 Bundle Contents:")
for key, value in model_bundle.items():
    if key != 'model':
        print(f"   {key}: {value}")

file_size = os.path.getsize('failsafe_model.pkl') / 1024
print(f"\n📏 File size: {file_size:.1f} KB")

# Download to your computer

import pandas as pd
import numpy as np

# ============================================
# PREPROCESSING PIPELINE
# ============================================

def preprocess_new_data(raw_df, feature_names):
    """
    Transform raw student data into model-ready format.

    Steps:
    1. Make a copy
    2. Encode binary columns (13 columns)
    3. One-hot encode multi-category columns (4 columns → 13 columns)
    4. Ensure column order matches training
    5. Fill any missing columns with 0
    """
    df = raw_df.copy()

    # ── Step 1: Encode binary columns ──
    binary_cols = ['school', 'sex', 'address', 'famsize', 'Pstatus',
                   'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
                   'higher', 'internet', 'romantic']

    binary_mappings = {
        'school': {'GP': 0, 'MS': 1},
        'sex': {'F': 0, 'M': 1},
        'address': {'U': 0, 'R': 1},
        'famsize': {'GT3': 0, 'LE3': 1},
        'Pstatus': {'A': 0, 'T': 1},
        'schoolsup': {'yes': 0, 'no': 1},
        'famsup': {'no': 0, 'yes': 1},
        'paid': {'no': 0, 'yes': 1},
        'activities': {'no': 0, 'yes': 1},
        'nursery': {'yes': 0, 'no': 1},
        'higher': {'yes': 0, 'no': 1},
        'internet': {'no': 0, 'yes': 1},
        'romantic': {'no': 0, 'yes': 1}
    }

    for col, mapping in binary_mappings.items():
        if col in df.columns:
            df[col] = df[col].map(mapping).fillna(0).astype(int)

    # ── Step 2: One-hot encode multi-category columns ──
    multi_cols = ['Mjob', 'Fjob', 'reason', 'guardian']

    for col in multi_cols:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col).astype(int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

    # ── Step 3: Ensure columns match training order ──
    # Add missing columns (if a category wasn't in new data)
    for col in feature_names:
        if col not in df.columns:
            df[col] = 0

    # Keep only training columns, in the right order
    df = df[feature_names]

    return df

print("✅ Preprocessing function created!")
print("\n📋 This function:")
print("   1. Encodes binary columns with correct mappings")
print("   2. One-hot encodes multi-category columns")
print("   3. Ensures same 41 columns as training data")
print("   4. Handles missing categories gracefully")

# Create a sample new student (simulating faculty upload)
new_student = pd.DataFrame([{
    'school': 'GP', 'sex': 'F', 'age': 17, 'address': 'U',
    'famsize': 'GT3', 'Pstatus': 'T', 'Medu': 2, 'Fedu': 2,
    'Mjob': 'other', 'Fjob': 'services', 'reason': 'course',
    'guardian': 'mother', 'traveltime': 2, 'studytime': 1,
    'failures': 1, 'schoolsup': 'no', 'famsup': 'yes',
    'paid': 'no', 'activities': 'no', 'nursery': 'yes',
    'higher': 'yes', 'internet': 'yes', 'romantic': 'no',
    'famrel': 3, 'freetime': 5, 'goout': 4, 'Dalc': 3,
    'Walc': 4, 'health': 2, 'absences': 20, 'G1': 6, 'G2': 5
}])

print("📋 RAW NEW STUDENT (33 columns):")
print(new_student[['age', 'absences', 'G1', 'G2', 'Walc']].to_string())

# Apply preprocessing
new_student_processed = preprocess_new_data(new_student, model_bundle['feature_names'])

print(f"\n✅ PROCESSED (41 columns):")
print(f"   Shape: {new_student_processed.shape}")

# Make prediction
prob_fail = model.predict_proba(new_student_processed)[0][0]
prediction = model.predict(new_student_processed)[0]

print(f"\n🎯 PREDICTION:")
print(f"   Probability of FAIL: {prob_fail:.1%}")
print(f"   Predicted class: {'FAIL ❌' if prediction == 0 else 'PASS ✅'}")

# SHAP explanation
student_shap = explainer.shap_values(new_student_processed)[0]
shap_df = pd.DataFrame({
    'feature': model_bundle['feature_names'],
    'shap_value': student_shap,
    'value': new_student_processed.values[0]
})
shap_df['abs_shap'] = abs(shap_df['shap_value'])
shap_df = shap_df.sort_values('abs_shap', ascending=False)

print(f"\n🔍 WHY THIS PREDICTION?")
for i, row in shap_df.head(5).iterrows():
    direction = "🟢 PROTECTIVE" if row['shap_value'] > 0 else "🔴 RISK"
    print(f"   {direction}: {row['feature']} (impact: {row['shap_value']:+.3f})")

# Add preprocessing function to the bundle
model_bundle['preprocessing'] = {
    'binary_mappings': {
        'school': {'GP': 0, 'MS': 1},
        'sex': {'F': 0, 'M': 1},
        'address': {'U': 0, 'R': 1},
        'famsize': {'GT3': 0, 'LE3': 1},
        'Pstatus': {'A': 0, 'T': 1},
        'schoolsup': {'yes': 0, 'no': 1},
        'famsup': {'no': 0, 'yes': 1},
        'paid': {'no': 0, 'yes': 1},
        'activities': {'no': 0, 'yes': 1},
        'nursery': {'yes': 0, 'no': 1},
        'higher': {'yes': 0, 'no': 1},
        'internet': {'no': 0, 'yes': 1},
        'romantic': {'no': 0, 'yes': 1}
    },
    'multi_cols': ['Mjob', 'Fjob', 'reason', 'guardian'],
    'expected_input_cols': 33
}

# Save updated bundle
joblib.dump(model_bundle, 'failsafe_model.pkl')

print("✅ Updated bundle saved with preprocessing config!")
print(f"\n📦 Bundle now contains:")
for key in model_bundle.keys():
    print(f"   → {key}")

# Re-download

# ============================================
# FINAL: Complete preprocessing code for backend
# ============================================

preprocessing_code = '''
import pandas as pd
import numpy as np

def preprocess_new_data(raw_df, feature_names):
    """Transform raw student data into model-ready format."""
    df = raw_df.copy()

    # Binary column mappings
    binary_mappings = {
        'school': {'GP': 0, 'MS': 1},
        'sex': {'F': 0, 'M': 1},
        'address': {'U': 0, 'R': 1},
        'famsize': {'GT3': 0, 'LE3': 1},
        'Pstatus': {'A': 0, 'T': 1},
        'schoolsup': {'yes': 0, 'no': 1},
        'famsup': {'no': 0, 'yes': 1},
        'paid': {'no': 0, 'yes': 1},
        'activities': {'no': 0, 'yes': 1},
        'nursery': {'yes': 0, 'no': 1},
        'higher': {'yes': 0, 'no': 1},
        'internet': {'no': 0, 'yes': 1},
        'romantic': {'no': 0, 'yes': 1}
    }

    for col, mapping in binary_mappings.items():
        if col in df.columns:
            df[col] = df[col].map(mapping).fillna(0).astype(int)

    # One-hot encode multi-category columns
    for col in ['Mjob', 'Fjob', 'reason', 'guardian']:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col).astype(int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

    # Ensure columns match training
    for col in feature_names:
        if col not in df.columns:
            df[col] = 0

    return df[feature_names]
'''

print(preprocessing_code)
print("\n📋 Copy the code above into your FastAPI backend!")
print("\n✅ GOOGLE COLAB PHASE COMPLETE!")
print("\n📦 Deliverables:")
print("   1. failsafe_model.pkl (downloaded)")
print("   2. Preprocessing function (above)")
print("   3. Full notebook (save this!)")



"""## 🧪 Verifying Model's Raw Data Handling

Let's ensure the saved `failsafe_model.pkl` correctly handles raw, unprepared data by applying its embedded preprocessing logic.
"""

import joblib
import pandas as pd

print("='*50")
print("💾 LOADING MODEL BUNDLE...")
print("='*50")

# Load the saved model bundle
loaded_bundle = joblib.load('failsafe_model.pkl')

# Extract model, feature names, and preprocessing configuration
loaded_model = loaded_bundle['model']
loaded_feature_names = loaded_bundle['feature_names']

print("✅ Model bundle loaded successfully!")
print(f"   Model type: {type(loaded_model)}")
print(f"   Expected features: {len(loaded_feature_names)}")

print("\n--- Reconstructing Preprocessing Function ---")

# Reconstruct the preprocess_new_data function (as it's not directly callable from a dict)
def preprocess_new_data_from_bundle(raw_df, feature_names, binary_mappings, multi_cols):
    df = raw_df.copy()

    # Binary column mappings
    for col, mapping in binary_mappings.items():
        if col in df.columns:
            df[col] = df[col].map(mapping).fillna(0).astype(int)

    # One-hot encode multi-category columns
    for col in multi_cols:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col).astype(int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

    # Ensure columns match training
    for col in feature_names:
        if col not in df.columns:
            df[col] = 0

    return df[feature_names]

# Get preprocessing configs from the bundle
binary_maps_from_bundle = loaded_bundle['preprocessing']['binary_mappings']
multi_cols_from_bundle = loaded_bundle['preprocessing']['multi_cols']

print("✅ Preprocessing function reconstructed using bundle configurations.")

# Create a sample raw student record
# This is similar to what the FastAPI backend would receive
sample_raw_student = pd.DataFrame([{
    'school': 'MS', 'sex': 'M', 'age': 16, 'address': 'R',
    'famsize': 'LE3', 'Pstatus': 'A', 'Medu': 1, 'Fedu': 1,
    'Mjob': 'other', 'Fjob': 'health', 'reason': 'reputation',
    'guardian': 'father', 'traveltime': 3, 'studytime': 2,
    'failures': 2, 'schoolsup': 'yes', 'famsup': 'no',
    'paid': 'yes', 'activities': 'yes', 'nursery': 'no',
    'higher': 'no', 'internet': 'no', 'romantic': 'yes',
    'famrel': 2, 'freetime': 1, 'goout': 5, 'Dalc': 5,
    'Walc': 5, 'health': 1, 'absences': 15, 'G1': 4, 'G2': 3
}])

print("\n--- Raw Sample Data ---")
print(f"Shape: {sample_raw_student.shape}")
display(sample_raw_student.head())

# Apply the reconstructed preprocessing function
print("\n--- Applying Preprocessing ---")
processed_student = preprocess_new_data_from_bundle(
    sample_raw_student,
    loaded_feature_names,
    binary_maps_from_bundle,
    multi_cols_from_bundle
)

print("✅ Data preprocessed successfully!")
print(f"   Shape after preprocessing: {processed_student.shape}")
print(f"   All columns are numeric: {all(processed_student.dtypes == 'int64')}")
print(f"   All expected features are present: {list(processed_student.columns) == loaded_feature_names}")
display(processed_student.head())

# Make a prediction with the loaded model and preprocessed data
print("\n--- Making Prediction with Processed Data ---")
probability_fail = loaded_model.predict_proba(processed_student)[0][0]
prediction = loaded_model.predict(processed_student)[0]

print(f"🎯 Probability of FAIL: {probability_fail:.1%}")
print(f"🎯 Predicted class: {'FAIL ❌' if prediction == 0 else 'PASS ✅'}")

print("\nThis confirms that the preprocessing logic and the model work together as expected with raw input data.")